name: Build JSON Resume

on:
  push:
    branches:
      - trunk
    paths-ignore:
      - 'docs'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node v14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
    - run: npm test
      name: Validate schema
    - run: npm run build --if-present
      name: Build HTML resume
    - run: npm run export --if-present
      name: Export PDF resume
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.14.0
      with:
        commit_message: Update GitHub pages
        file_pattern: docs
